/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./*.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "deep-navy": "#12205C",
        "outline": "#767681",
        "on-secondary-container": "#715000",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dee1ff",
        "on-secondary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#4a4829",
        "surface": "#fcf9f8",
        "inverse-surface": "#303030",
        "surface-tint": "#4e5a98",
        "on-primary-container": "#7d89cb",
        "vibrant-gold": "#F4B93E",
        "primary": "#000a3e",
        "tertiary-fixed-dim": "#ccc8a0",
        "pure-white": "#FFFFFF",
        "on-tertiary-container": "#424023",
        "on-surface-variant": "#454650",
        "surface-variant": "#e4e2e1",
        "on-primary-fixed": "#041452",
        "on-tertiary-fixed": "#1e1c04",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-error-container": "#93000a",
        "tertiary-container": "#b0ac86",
        "secondary-fixed": "#ffdea6",
        "inverse-on-surface": "#f3f0f0",
        "error": "#ba1a1a",
        "cream-canvas": "#F7F2C8",
        "primary-container": "#12205c",
        "outline-variant": "#c6c5d1",
        "on-secondary-fixed-variant": "#5e4200",
        "primary-fixed-dim": "#b9c3ff",
        "inverse-primary": "#b9c3ff",
        "surface-dim": "#dcd9d9",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed-variant": "#36427f",
        "surface-container": "#f0eded",
        "error-container": "#ffdad6",
        "secondary": "#7c5800",
        "secondary-fixed-dim": "#f8bd42",
        "surface-container-highest": "#e4e2e1",
        "background": "#fcf9f8",
        "on-surface": "#1b1c1c",
        "surface-container-high": "#eae7e7",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary": "#62603f",
        "tertiary-fixed": "#e9e4bb",
        "secondary-container": "#fec247",
        "on-background": "#1b1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "display-xl": ["Plus Jakarta Sans"],
        "label-caps": ["JetBrains Mono"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "800" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
